[package]
name = "zon-inspector"
version = "0.1.0"
edition = "2021"
description = "CLI tool to inspect and convert ZON files to JSON."
license = "MIT"

[[bin]]
name = "zon-inspector"
path = "src/main.rs"

[dependencies]
zon-core = { path = "../zon-core" }
serde_json = "1.0"
